---
- name: "Setting up Dev Workstation"
  hosts: "localhost"
  vars:
    this_user: "{{ ansible_user_id }}"
  vars_files:
    - vars/configs.yml

  tasks:
    - name: "Install Nodejs"
      package:
        name: nodejs
        state: present
      become: true

    - name: "Install Rust"
      shell: |
        set -o pipefail
        curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: "$HOME/.cargo/bin/rustup"
        executable: /bin/bash

    - name: "Install Utils"
      package: name={{item}}
      with_items:
        - tmux 
        - fzf
        - ripgrep
        - fd-find
        - neovim
      become: true

    - name: "Install Proximity Sort"
      shell: |
        set -o pipefail
        cargo install proximity-sort
      args:
        creates: "$HOME/.cargo/bin/proximity-sort"
        executable: /bin/bash

    - name: "Sync dotfiles"
      shell: |
        set -o pipefail
        git clone --separate-git-dir=$HOME/.dotfiles {{ config_git }} tmpdotfiles
        rsync --recursive --verbose --exclude '.git' tmpdotfiles/ $HOME/
        rm -r tmpdotfiles
      args:
        creates: "$HOME/.dotfiles"
        executable: /bin/bash

    - name: "Install Zsh"
      package:
        name: zsh
      become: true
    
    - name: "Install oh-my-zsh"
      shell: |
        set -o pipefail
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "$HOME/.oh-my-zsh"
        executable: /bin/bash

    - name: "Set Zsh as default shell"
      become: true
      user:
        name: "{{ this_user }}"
        shell: /bin/zsh

    - name: "Install Neovim Plugins"
      shell: |
        set -o pipefail
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        nvim -es -u $HOME/.config/nvim/init.vim -i NONE -c "PlugInstall" -c "qa"
